<?php
namespace frontend\widgets;

use backend\models\GoodsCategory;

use yii\base\Widget;

class CategoryWidget extends Widget{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
//    public function run()
//    {
//
//        //检测redis是否存在
//
//
//        $categories = GoodsCategory::findAll(['parent_id'=>0]);
//        $category_html = $this->renderFile('@app/widgets/view/category.php',['categories'=>$categories]);
//
//        return $category_html;
//    }
    public function run()
    {
        //检测redis是否有商品分类缓存
        $redis = new \Redis();

       $redis->connect('127.0.0.1');
//       $redis->flushAll();
        $category_html = $redis->get('category_html');
        if($category_html==null){

        $categories = GoodsCategory::findAll(['parent_id'=>0]);
        $category_html = $this->renderFile('@app/widgets/view/category.php',['categories'=>$categories]);

            $redis->set('category_html',$category_html);
            $redis->expire('category_html',3600*12);
        }
        return $category_html;




    }
}